import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import { Header } from "@/components/header";

const be_vietnam_pro = Be_Vietnam_Pro({ 
  subsets: ["latin"], 
  variable: "--font-be-vietnam-pro",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={be_vietnam_pro.className}>
      <body>
      <div className="flex flex-col max-w-7xl min-h-screen mx-auto bg-white/[2%]">
        <Header />
        {children}
        <Footer />
      </div>
      </body>
    </html>
  );
}
